name: karbarab
description: Belajar Kartu Bahasa Arab

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.4
  cupertino_icons: ^0.1.3
  flutter_flip_view: ^1.0.3
  confetti: ^0.3.0
  audioplayer: ^0.5.2
  path_provider: ^1.6.4
  http: ^0.12.0+4

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/launcher/icon---.png"
  image_path_android: "lib/assets/launcher/icon---.png"
  adaptive_icon_background: "lib/assets/launcher/background--.png"
  adaptive_icon_foreground: "lib/assets/launcher/foreground---.png"

flutter:
  uses-material-design: true
  assets:
    - character.png
    - card-logo.png
    - google_logo.png
    - neutral-triangle-right.png
    - congratulation.png
    - table.png
    - character-.png
    - congrat-character.png
    - bunga.mp3
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/proxima-nova-regular.otf
    - family: FTF-Ahlan
      fonts:
        - asset: fonts/ftf-ahlan-ve-arabez.ttf
    - family: Geeza
      fonts:
        - asset: fonts/geeza-pro.ttc
