name: karbarab
description: Belajar Kartu Bahasa Arab

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  animate_do: ^1.2.1
  cupertino_icons: ^0.1.3
  confetti: ^0.3.0
  cloud_firestore: ^0.13.4+2
  equatable: ^1.1.0
  firebase_auth: ^0.15.4
  flutter_flip_view: ^1.0.3
  flutter_bloc: ^3.2.0
  firebase_crashlytics: ^0.1.3
  google_sign_in: ^4.1.4
  meta: ^1.1.6
  uuid: 2.0.4
  flutter_spinkit: "^2.1.0"
  flutter:
    sdk: flutter
  flutter_audio_player:
    git:
      url: git://github.com/hui-z/audio_player.git
      ref: master-androidx

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon---.png"
  image_path_android: "assets/launcher/icon---.png"
  adaptive_icon_background: "assets/launcher/background--.png"
  adaptive_icon_foreground: "assets/launcher/foreground---.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/character.png
    - assets/images/card_logo.png
    - assets/images/google_logo.png
    - assets/images/congratulation_character.png
    - assets/images/neutral_triangle_right.png
    - assets/voices/
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/proxima-nova-regular.otf
    - family: FTF-Ahlan
      fonts:
        - asset: fonts/ftf-ahlan-ve-arabez.ttf
    - family: Geeza
      fonts:
        - asset: fonts/geeza-pro.ttc
