name: karbarab
description: Belajar Kartu Bahasa Arab

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  android_intent: ^0.3.6+1
  animate_do: ^1.2.1
  confetti: ^0.3.0
  cloud_firestore: ^0.13.4+2
  equatable: ^1.1.0
  firebase_auth: ^0.15.4
  flutter_flip_view: ^1.0.3
  flutter_bloc: ^3.2.0
  firebase_crashlytics: ^0.1.3
  firebase_messaging: ^6.0.13
  logger: ^0.6.0
  google_sign_in: ^4.1.4
  meta: ^1.1.6
  uuid: 2.0.4
  flutter_spinkit: "^2.1.0"
  firebase_admob: ^0.9.3
  http: ^0.12.0+4
  path_provider: ^1.6.5
  audioplayers: ^0.14.2
  shared_preferences: ^0.5.6+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon---.png"
  image_path_android: "assets/launcher/icon---.png"
  adaptive_icon_background: "assets/launcher/background--.png"
  adaptive_icon_foreground: "assets/launcher/foreground---.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/character.png
    - assets/images/no-photo.jpg
    - assets/images/card_logo.png
    - assets/images/google_logo.png
    - assets/images/congratulation_character.png
    - assets/images/neutral_triangle_right.png
    - assets/quiz/
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/proxima-nova-regular.otf
    - family: FTF-Ahlan
      fonts:
        - asset: fonts/ftf-ahlan-ve-arabez.ttf
    - family: Geeza
      fonts:
        - asset: fonts/geeza-pro.ttc
