name: karbarab
description: Belajar Kartu Bahasa Arab

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.4
  cupertino_icons: ^0.1.3
  flutter_flip_view: ^1.0.3
  confetti: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/launcher/icon---.png"
  image_path_android: "lib/assets/launcher/icon---.png"
  adaptive_icon_background: "lib/assets/launcher/background--.png"
  adaptive_icon_foreground: "lib/assets/launcher/foreground---.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/character.png
    - lib/assets/images/card_logo.png
    - lib/assets/images/google_logo.png
    - lib/assets/images/neutral_triangle_right.png
    - lib/assets/voices/
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/proxima-nova-regular.otf
    - family: FTF-Ahlan
      fonts:
        - asset: fonts/ftf-ahlan-ve-arabez.ttf
    - family: Geeza
      fonts:
        - asset: fonts/geeza-pro.ttc
